### ISSUE TITLE
pkgdown site should have some organization to the reference pages

### ISSUE THREAD

**Issue by richardsc** [dankelley/oce#1689]
See here: https://pkgdown.r-lib.org/articles/pkgdown.html#reference

Basically, we can organize the reference pages in a way that makes sense (e.g. by topic) rather than just alphabetically. Considering there are so many, I think this would be a good idea because of the value of being able to browse such pages.

I don't like the idea of having to hand-curate all the topics, but we might have to. The linked page above gives some suggestions on how to use functions like `starts_with()` and `matches()` to pull out groups of pages (unfortunately I'm not sure `oce` has been consistent enough with function prefixes to make that a viable route though ...). Below is an example of how to modify the `_pkgdown.yml` to curate the reference section:

```
reference:
- title: "Connecting to Spark"
  desc: >
    Functions for installing Spark components and managing
    connections to Spark
- contents: 
  - spark_config
  - spark_connect
  - spark_disconnect
  - spark_install
  - spark_log
- title: "Reading and Writing Data"
  desc: "Functions for reading and writing Spark DataFrames."
- contents:
  - starts_with("spark_read")
  - starts_with("spark_write")
  - matches("saveload")
```

@dankelley @clayton33 -- any suggestions as to good topics to organize the help pages?
