### ISSUE TITLE
read.argo()[["HISTORY_QCTEST"]] length is wrong

### ISSUE THREAD

**Issue by dankelley** [dankelley/oce#1703]
In a vf2f meeting today about the argoFloats project (e.g. https://github.com/ArgoCanada/argoFloats/issues/134),  it became clear that `read.argo()` is incorrectly repeating the `HISTORY_QCTEST` value to be of the same length as the pressure column(s).  That is wrong.  It should retain the dimension that it has in the netcdf file.

**Comment by dankelley** [comment]
I wish I had written down an ID/profile pair, because I am having trouble checking into this bug. The code below works fine
```R
library(ncdf4)
library(oce)
#source("~/git/oce/R/argo.R")
files <- c("~/git/oce/create_data/argo/6900388_prof.nc", "~/data/argo/D3900740_193.nc")
for (file in files) {
    if (file.exists(file)) {
        a <- read.argo(file)
        n <- nc_open(file)
        hqt <- ncvar_get(n, "HISTORY_QCTEST")
        stopifnot(all.equal(a[["HISTORY_QCTEST"]], gsub("[ ]*$", "", hqt)))
        message("HISTORY_QCTEST is ok in '", file, "'")
    } else {
        message("cannot check '", file, "' because it is not on this filesystem")
    }
}
```

**Comment by dankelley** [comment]
I feel there is no bug here.  Below is what is stored in a netcdf file that I examined:
```
        char HISTORY_QCTEST[STRING16,N_PROF,N_HISTORY]   
            long_name: Documentation of tests performed, tests failed (in hex form)
            conventions: Write tests performed when ACTION=QCP$; tests failed when ACTION=QCF$
            _FillValue:  
```
and this is a funky way of saying that we have a matrix with `N_PROF` rows and `N_HISTORY` columns, which each entry being a string of 16 characters.  And that is what I am getting for test files.
